export default {
  absolute00s: {
    url: 'https://absoluteradio.co.uk/00s/music/',
    name: 'absolute00s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  absolute90s: {
    url: 'https://absoluteradio.co.uk/90s/music/',
    name: 'absolute90s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  absolute80s: {
    url: 'https://absoluteradio.co.uk/80s/music/',
    name: 'absolute80s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  absolute70s: {
    url: 'https://absoluteradio.co.uk/70s/music/',
    name: 'absolute70s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  absolute60s: {
    url: 'https://absoluteradio.co.uk/60s/music/',
    name: 'absolute60s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  classicRock: {
    url: 'https://absoluteradio.co.uk/classic-rock/music/',
    name: 'classic-rock',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  absoluteRadio: {
    url: 'https://absoluteradio.co.uk/absolute-radio/music/',
    name: 'absolute-radio',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
  },
  sixMusic: {
    url: 'https://www.bbc.co.uk/music/tracks/find/6music',
    name: 'six-music',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
  },
  radioOne: {
    url: 'http://www.bbc.co.uk/radio1',
    name: 'radio-one',
    trackSelector: '.on-air__track-now-playing__title',
    artistSelector: '.on-air__track-now-playing__artist',
  },
  oneXtra: {
    url: 'https://www.bbc.co.uk/music/tracks/find/1xtra',
    name: 'one-xtra',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
  },
  radioTwo: {
    url: 'https://www.bbc.co.uk/music/tracks/find/radio2',
    name: 'radio-two',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
  },
  asianNetwork: {
    url: 'https://www.bbc.co.uk/music/tracks/find/asiannetwork',
    name: 'asian-network',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
  },
  kisstory: {
    url: 'https://planetradio.co.uk/kisstory/',
    name: 'kisstory',
    trackSelector: '.play-bar-artist-track',
    artistSelector: '.play-bar-artist',
  },
  radioX: {
    url: 'http://www.radiox.co.uk/playlist/',
    name: 'radioX',
    trackSelector: '.track',
    artistSelector: '.artist',
    omit: ['\n'],
  },
  planetRock: {
    url: 'http://www.planetrock.com/',
    name: 'planetRock',
    trackSelector: '.c-now-playing__song',
    artistSelector: '.c-now-playing__link',
    splitTrackAfter: ['-'],
  },
  jazzFm: {
    url: 'http://www.jazzfm.com/music/',
    name: 'jazzFm',
    trackSelector: '.now-playing-now',
    artistSelector: '.now-playing-now',
    omit: ['\r\n', 'Now\r\n', 'Download\r\n'],
    splitTrackAfter: ['-'],
    splitArtistAfter: ['-'],
  },
  listenToThisNew: {
    url: 'https://www.reddit.com/r/listentothis/new/',
    name: 'listenToThisNew',
    trackSelector: '.entry .title .may-blank',
    artistSelector: '.entry .title .may-blank',
    splitTrackAfter: ['['],
    splitTrackBefore: ['--'],
    splitArtistAfter: ['--'],
  },
}
