import firebase from './initialiseFirebase.js'

firebase.database().ref('/sources').update({
  absolute00s: {
    url: 'https://absoluteradio.co.uk/00s/music/',
    name: 'absolute00s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  absolute90s: {
    url: 'https://absoluteradio.co.uk/90s/music/',
    name: 'absolute90s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  absolute80s: {
    url: 'https://absoluteradio.co.uk/80s/music/',
    name: 'absolute80s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  absolute70s: {
    url: 'https://absoluteradio.co.uk/70s/music/',
    name: 'absolute70s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  absolute60s: {
    url: 'https://absoluteradio.co.uk/60s/music/',
    name: 'absolute60s',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  classicRock: {
    url: 'https://absoluteradio.co.uk/classic-rock/music/',
    name: 'classicRock',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  absoluteRadio: {
    url: 'https://absoluteradio.co.uk/absolute-radio/music/',
    name: 'absoluteRadio',
    trackSelector: '.song-title a',
    artistSelector: '.song-artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  sixMusic: {
    url: 'https://www.bbc.co.uk/music/tracks/find/6music',
    name: 'sixMusic',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  radioOne: {
    url: 'http://www.bbc.co.uk/radio1',
    name: 'radioOne',
    trackSelector: '.on-air__track-now-playing__title',
    artistSelector: '.on-air__track-now-playing__artist',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  oneXtra: {
    url: 'https://www.bbc.co.uk/music/tracks/find/1xtra',
    name: 'oneXtra',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  radioTwo: {
    url: 'https://www.bbc.co.uk/music/tracks/find/radio2',
    name: 'radioTwo',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  asianNetwork: {
    url: 'https://www.bbc.co.uk/music/tracks/find/asiannetwork',
    name: 'asianNetwork',
    trackSelector: '.music-track__title',
    artistSelector: '.music-track__artist--link',
    omit: ['\\.', '#', '$', '[', ']'],
  },
  kisstory: {
    url: 'https://planetradio.co.uk/kisstory/',
    name: 'kisstory',
    trackSelector: '.play-bar-artist-track',
    artistSelector: '.play-bar-artist',
    omit: ['\\.', '#', '$', '[', ']', '-'],
  },
  radioX: {
    url: 'http://www.radiox.co.uk/playlist/',
    name: 'radioX',
    trackSelector: '.track',
    artistSelector: '.artist',
    omit: ['\\n', '\\.', '#', '$', '[', ']', '-', '  '],
  },
  planetRock: {
    url: 'http://www.planetrock.com/',
    name: 'planetRock',
    trackSelector: '.c-now-playing__song',
    artistSelector: '.c-now-playing__link',
    dropTrackBefore: '-',
    omit: ['\\.', '#', '$', '[', ']', '-'],
  },
  jazzFm: {
    url: 'http://www.jazzfm.com/music/',
    name: 'jazzFm',
    trackSelector: '.now-playing-now',
    artistSelector: '.now-playing-now',
    omit: ['\\r\\n', 'Now\\r\\n', 'Download\\r\\n', '\\.', '#', '$', '[', ']', '  '],
    dropTrackAfter: '-',
    dropArtistBefore: '-',
  },
  listenToThisNew: {
    url: 'https://www.reddit.com/r/listentothis/new/',
    name: 'listenToThisNew',
    trackSelector: '.entry .title .may-blank',
    artistSelector: '.entry .title .may-blank',
    dropTrackAfter: '[',
    dropTrackBefore: '--',
    dropArtistAfter: '--',
    omit: ['\\.', '#', '$', '[', ']'],
  },
})
